### ISSUE TITLE
`sum` always return string

### ISSUE THREAD

**Issue by mamlzy** [eoin-obrien/prisma-extension-kysely#167]
Im using prisma with mysql, why doing `sum` always return a string, can you help me why? thanks!

**Comment by eoin-obrien** [comment]
Hi, and thanks for using this extension!

Check out the Kysely documentation for sum here: [https://kysely-org.github.io/kysely-apidoc/interfaces/FunctionModule.html#sum](https://kysely-org.github.io/kysely-apidoc/interfaces/FunctionModule.html#sum). You might need to cast it on the DB side, depending on what you're trying to do. Hope that helps!

**Comment by mamlzy** [comment]
thanks for your response @eoin-obrien, they have docs for type casting on DB side, here is the link https://kysely.dev/docs/recipes/data-types. But how to do it with `prisma-kysely`? that example only for `kysely` without `prisma`, can you help me?
