### ISSUE TITLE
CamelCasePlugin Support

### ISSUE THREAD

**Issue by luap2703** [eoin-obrien/prisma-extension-kysely#29]
**Is your feature request related to a problem? Please describe.**
Hi! First of all amazing plugin! Great work, we wanted to do the same and now are just using yours :)

Atm CamelCasePlugin does not correctly work. The returned items are still snake_case. I think it would be easily achievable to check if CamelCase Plugin is active and if yes, manually rewrap the result in the `transformResult()` function.

Normally the engine/driver would do it, but as thus this plugin is only used as query builder, it won't be done automatically.

Thank you and greetings from Germany!
Paul

**Comment by eoin-obrien** [comment]
> Hi! First of all amazing plugin! Great work, we wanted to do the same and now are just using yours :)

Danke schön! I'm delighted to know the plugin was useful for you. :)

> Atm CamelCasePlugin does not correctly work. The returned items are still snake_case. I think it would be easily achievable to check if CamelCase Plugin is active and if yes, manually rewrap the result in the transformResult() function.
>
> Normally the engine/driver would do it, but as thus this plugin is only used as query builder, it won't be done automatically.

This should be pretty straightforward to implement! I've taken a quick look at Kysely's plugin API, and unfortunately, we can't get a list of plugins from the `Kysely` object after it's been constructed, though we can add more with `.withPlugin()`.

To me, the simplest workaround would be to pass the list of plugins to the `kyselyExtension()` function as well, so it can call `transformResult()` as appropriate.

For example:

```typescript
const prisma = new PrismaClient().$extends(
  kyselyExtension({
    kysely: new Kysely<DB>({
      dialect: { /* ... */ },
    }),
    /* prisma-extension-kysely will invoke transformResult() from these plugins: */
    plugins: [
      new CamelCasePlugin(),
    ],
  }),
);
```

Under the hood, these plugins will be added to the `prisma.$kysely` object using `.withPlugin()`, and their `transformResult()` functions will be invoked on all query results.

Does this seem like the best solution for your use case? If so, I should be able to get it coded up, documented and released swiftly!

**Comment by mhaagens** [comment]
Would love this feature as well!

**Comment by eoin-obrien** [comment]
This turned out to be a little more complex than I thought it would be at first glance, but it's pretty much ready to release as part of v2.0.0 of the extension! By hooking into Kysely's driver class, I've managed to enable support for all Kysely plugins, not just `CamelCasePlugin`. Keep an eye out for PR #37 being merged! Feel free to test it out in the meantime too.
