### ISSUE TITLE
Type '(driver: Driver) => Kysely<DB>' is not assignable to type 'Kysely<unknown>'

### ISSUE THREAD

**Issue by SooditK** [eoin-obrien/prisma-extension-kysely#39]
**Describe the bug**
I copied the basic example and found that it does not work well with typescript
It throws the following error:
`Type '(driver: Driver) => Kysely<DB>' is not assignable to type 'Kysely<unknown>'`

**To Reproduce**
1. You can create a basic express and prisma project (you can use `npx try-prisma@latest` and select `rest-express`)
2. You install all the required dependencies (prisma-kysely, prisma-extension-kysely & kysely)
3. Add the following code to `schema.prisma` file:
```prisma
generator kysely {
  provider     = "prisma-kysely"
  output       = "../src/db"
  fileName     = "types.ts"
  enumFileName = "enums.ts"
}
```
4. Run `npx prisma generate`
5. Create a new file and can extend prisma there (like following):
```ts
import { PrismaClient } from "@prisma/client";
import {
  Driver,
  Kysely,
  SqliteAdapter,
  SqliteIntrospector,
  SqliteQueryCompiler,
} from "kysely";
import kyselyExtension from "prisma-extension-kysely";
import type { DB } from "./types";

const prisma = new PrismaClient().$extends(
  kyselyExtension({
    kysely: (driver: Driver) =>
      new Kysely<DB>({
        dialect: {
          createAdapter: () => new SqliteAdapter(),
          createDriver: () => driver,
          createIntrospector: (db) => new SqliteIntrospector(db),
          createQueryCompiler: () => new SqliteQueryCompiler(),
        },
      }),
  })
);
```

**Expected behavior**
The type error shouldn't be there

**Screenshots**
![image](https://github.com/eoin-obrien/prisma-extension-kysely/assets/50576944/1a5d5253-884f-45d7-975c-2690c3055700)

**Desktop (please complete the following information):**

- OS: macOS Sonoma 14.2.1 (23C71)

**Additional context**
here's the `tsconfig.json` if your reference:

```json
{
  "compilerOptions": {
    "sourceMap": true,
    "outDir": "dist",
    "strict": true,
    "lib": ["esnext"],
    "esModuleInterop": true
  }
}
```

**Comment by eoin-obrien** [comment]
It looks like you're using the example from the latest (unreleased) version of the package! It's for v2.0.0, which should be released soon.

Try using the example at https://github.com/eoin-obrien/prisma-extension-kysely/tree/v1.0.4 - that should match the currently released version of the package.
