### ISSUE TITLE
Type error in NodeJS 20, when lib: ["es2023"]

### ISSUE THREAD

**Issue by SooditK** [eoin-obrien/prisma-extension-kysely#43]
**Describe the bug**
I'm using NodeJS 20 and the following `tsconfig.json` for my expressjs application, Prisma Extension Kysely throws Type Error:
`Type 'typeof import("PATH_TO_MY_PROJECT/node_modules/prisma-extension-kysely/dist/index")' has no call signatures.`

**To Reproduce**

1. You can create a basic express and prisma project (you can use npx try-prisma@latest and select rest-express)
2. You install all the required dependencies (prisma-kysely, prisma-extension-kysely & kysely)
3. Add the following code to schema.prisma file:
```prisma
generator kysely {
  provider     = "prisma-kysely"
  output       = "../src/db"
  fileName     = "types.ts"
  enumFileName = "enums.ts"
}
```
4. Run `npx prisma generate`
5. Create a new file and can extend prisma there (like following):
```ts
import kyselyExtension from "prisma-extension-kysely";
import type { DB } from "./types.js";  // <--- the '.js' extension cuz Relative import paths need explicit file extensions in ECMAScript imports when --moduleResolution is node16
import { PrismaClient } from "@prisma/client";
import {
  Kysely,
  SqliteAdapter,
  SqliteIntrospector,
  SqliteQueryCompiler,
  Driver,
} from "kysely";

export const prisma = new PrismaClient().$extends(
  kyselyExtension({ // <--- ERROR: This expression is not callable.
    kysely: (driver: Driver) =>
      new Kysely<DB>({
        dialect: {
          createDriver: () => driver,
          createAdapter: () => new SqliteAdapter(),
          createIntrospector: (db) => new SqliteIntrospector(db),
          createQueryCompiler: () => new SqliteQueryCompiler(),
        },
        plugins: [],
      }),
  })
);
```

**Expected behavior**
No Type Errors 😄 

**Desktop (please complete the following information):**

- OS: macOS Sonoma 14.2.1 (23C71)

**Additional context**
`tsconfig.json`:

```json
{
  "compilerOptions": {
    "lib": ["es2023"],
    "module": "node16",
    "target": "es2022",
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node16",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "noImplicitThis": true,
    "allowJs": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": "dist/"
  },
  "exclude": ["node_modules"],
  "include": ["src/**/*"],
  "ts-node": {
    "esm": true,
    "experimentalSpecifierResolution": "node"
  }
}
```

**Comment by SooditK** [comment]
Hii! here's the link: https://github.com/SooditK/prisma-extension-kysely-typeissue
You can use any package manager (bun works as well)
Please do `npm i` and then add your Database Credentials in `.env`
after that, you can do `npx prisma db push` and you'll see the error in `src/index.ts` & `src/db/prisma.ts`
Optionally, you can do `npx prisma db seed` to seed the DB with dummy data

Thanks

**Comment by eoin-obrien** [comment]
Looks like an ESM vs CJS issue! I'll dig into it and let you know when I've got a solution posted. Thanks again!

**Comment by eoin-obrien** [comment]
This looks like it's been resolved by the new release! Using your sample repo:

```shell
npm install prisma-extension-kysely@latest
npm run build
npm run dev
``` 

It now works without any type errors! Thanks again for bringing this to my attention, much appreciated.
