### ISSUE TITLE
Inserting/Updating enums | Auto-casting

### ISSUE THREAD

**Issue by luap2703** [eoin-obrien/prisma-extension-kysely#72]
**Is your feature request related to a problem? Please describe.**
Again, really amazing extension! Not sure if this is smth that should be handled by the integration, but one issue we are having quite frequently at the moment is the following: When inserting values that contain an enum (defined as an enum in the db schema), the typescript compiler says our insert is ok, but during execution, the operation will fail as the inserted enum in typescript does not get transformed to the db level enum type. Thus, we have to unwrap the inserted object/array just to (by knowing that smth is an enum) and cast it using sql``::enum. 

**Describe the solution you'd like**
Is there any way that this could be already handled by the plugin/extension? Given that it knows what values are enums defined by Prisma, could the plugin just automatically add the enum cast? 

This would save us hours in debugging and manual (and untyped!!) changes.

**Additional context**
Please find a screenshot attached of what we mean.

<img width="584" alt="Screenshot 2024-03-01 at 15 09 40" src="https://github.com/eoin-obrien/prisma-extension-kysely/assets/70726673/97c3b482-3686-49f7-ba8d-fd5e2494cafa">
<img width="983" alt="Screenshot 2024-03-01 at 15 10 50" src="https://github.com/eoin-obrien/prisma-extension-kysely/assets/70726673/5a3b04ef-2ad3-4260-ada1-3e418e5ed620">

**Comment by luap2703** [comment]
To provide some further input:
 The function to cast the respective enums would be quite easy, the magic would just be to automatically assign the function whenever there is an enum inserted.

See here https://github.com/kysely-org/kysely/issues/198

**Comment by maxdeichmann** [comment]
Hi, is there any update on this?

**Comment by MrVhek** [comment]
This looks like a prisma-kysely or kysely issue.

**Comment by eoin-obrien** [comment]
Thanks for using the extension! I've thought about this one, and it feels like it's out of scope for `prisma-extension-kysely`. Adding magic casts increases the surface area for testing, and would make the behaviour of the extension different from pure Kysely; both of these are scenarios I'd like to avoid. A helper function being added to `prisma-kysely` or enum helpers for Kysely itself would probably be the best option!
