### ISSUE TITLE
Types Mismatch for postgres scalar lists

### ISSUE THREAD

**Issue by raaaaayn** [eoin-obrien/prisma-extension-kysely#91]
## **Describe the bug**
nullable columns reported as non nullable

## **To Reproduce**
clone this [example repo](https://github.com/raaaaayn/prisma-kysely-null-scalar-lists) and
- `docker compose up` to start postgres
- `npm install && npx prisma migrate dev && npx prisma db seed`
- `npm run dev` to start the next app

## **Expected behavior**
Expected Generated Types for scalar lists such as `text[]` `integer[]` `json[]` to be nullable

**Model Definition**
```prisma
...

generator kysely {
  provider = "prisma-kysely"
}

...

model TestModel {
  id Int @id @default(autoincrement())

  list1 String[]
  list2 Int[]
  list3 Json[]
}

```

**Postgres schema inspected after running prisma migrations**
<img width="670" alt="image" src="https://github.com/eoin-obrien/prisma-extension-kysely/assets/12910777/ad19ff62-c1a4-4893-8cab-a633f6ee44e9">

**Versions:**

- @prisma/client: ^5.12.1
- kysely: ^0.27.3
- next: 14.2.2
- prisma-extension-kysely: ^2.1.0

## **Additional context**
Noticed this bug when my website crashed in prod, I was able to reproduce this bug pretty easily and I don't think its a prisma/prisma-keysely version issue.

I have two api's that I'm calling which do almost the same query but one is through prisma the other one is through prisma-kysely

```ts
prisma.testModel.findFirst();
```

```ts
prisma.$kysely
    .selectFrom("TestModel")
    .selectAll()
    .limit(1)
    .execute();
```

and here's what the result looks like:
- prisma select
```json
{
  "id": 1,
  "list1": [],
  "list2": [],
  "list3": []
}
```
- prisma-kysely select
```json
{
  "id": 1,
  "list1": null,
  "list2": null,
  "list3": null
}
```
and here's what the reported types look like:
- prisma select
<img width="247" alt="image" src="https://github.com/eoin-obrien/prisma-extension-kysely/assets/12910777/a7b2546a-3f51-4cda-b2f1-1dab7a0211b3">

- prisma-kysely select
<img width="176" alt="image" src="https://github.com/eoin-obrien/prisma-extension-kysely/assets/12910777/e5a837c8-8ca4-4a54-8090-293c9ac16a74">

You can find the api endpoints at `/api/test` and `/api/test-kysely` in my example repo. please follow the setup instructions mentioned in the "**To Reproduce**" section.

If someone can point me in the right direction I will be more than happy to dig into this and hopefully create a PR to solve this in the near future

**Comment by MrVhek** [comment]
This is most probably a kysely and/or prisma issue. The way of handling types differ between prisma and kysely, which is why you may need to do some cast.

**Comment by eoin-obrien** [comment]
Thanks for using `prisma-extension-kysely`! Type generation from the Prisma schema is all handled by [prisma-kysely](https://github.com/valtyr/prisma-kysely), as @MrVhek pointed out! Take a look at their type overrides, or ask this question over on that repo. It's not something that the extension can address.
